/* google-auth.js
 * This library provide decode for otpauth-migration link into otp secret.
 * It is entirely generated by ChatGPT 4o
 */

async function decodeMigrationUri(uri) {
    if (!uri.startsWith("otpauth-migration://")) {
        throw new Error("Invalid otpauth-migration URI");
    }

    const base64Data = uri.split("data=")[1];

    // Use the new CSP-safe decoder from standalone migration.js
    const payload = decodeMigrationPayload(base64Data);

    const toBase32 = (bytes) => {
        const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";
        let bits = 0, value = 0, output = "";

        for (let i = 0; i < bytes.length; i++) {
            value = (value << 8) | bytes[i];
            bits += 8;
            while (bits >= 5) {
                output += alphabet[(value >>> (bits - 5)) & 31];
                bits -= 5;
            }
        }

        if (bits > 0) {
            output += alphabet[(value << (5 - bits)) & 31];
        }

        return output;
    };

    return payload.otp_parameters.map(entry => ({
        name: entry.name || "",
        issuer: entry.issuer || "",
        secret: toBase32(entry.secret)
    }));
}
